### ISSUE TITLE
configure poppler

### ISSUE THREAD

**Issue by nicolasfranck** [c9s/perl-poppler#4]
Thanks for this module! There is not so much around to handle pdf.

pdftotext (from poppler-utils) also uses the "globalParams" (GlobalParams) to configure
poppler. Is there any way to do this in this module?

**Comment by jvolkening** [comment]
This module uses the [glib interface](https://people.freedesktop.org/~ajohnson/docs/poppler-glib/) -- along with gobject introspection -- which doesn't include the GlobalParams class. What is your use case?

**Comment by nicolasfranck** [comment]
I'm trying to extra text data from a pdf, using:
```
  $page = $pdf->get_page(0);
  $page->get_text();
```
Apparently, a "form feed" is added to the end of every text block.
In "pdftotext" this default behaviour can be disabled by using the parameter 
"-nopgbrk" which sets GlobalParams internally. But I do not know of
another way to influence this library.

**Comment by jvolkening** [comment]
Not sure why you're seeing different behavior - there are no line feeds added on my system (using the perl code, that is). I don't _think_ the poppler libs read from xpdfrc or anywhere else that I'm aware to set local configuration. You could of course check for them using perl after extracting each page but that may seem a bit untidy. You might try asking on the poppler lists. This module is just a thin layer over poppler-glib and so any answers you get there would be applicable here.

**Comment by nicolasfranck** [comment]
I'm not sure who to address. The main project on github

https://github.com/davidben/poppler

seems to have stopped since 2010. Searching for poppler on github
delivers some forks, but no real successors. Is this project dead?

**Comment by jvolkening** [comment]
Not dead at all - I think poppler is central to some of the most widely used PDF-related software in Linux, and the last stable release was two weeks ago. Development doesn't happen on Github, though. See the main page [here](https://poppler.freedesktop.org/). It has links to the main git repository as well as the mailing list (which is where you will probably have the most luck with your question).

**Comment by nicolasfranck** [comment]
ah right! I had forgotten about that website ;-) Thanks for your information!

**Comment by nicolasfranck** [comment]
Too bad. They sent me back here ;-)

    https://lists.freedesktop.org/archives/poppler/2016-December/012026.html

If I look at the source code of Poppler::Document (in C), I see that an object of
class "GlobalParams" is created when not defined, and then used as configuration
object:

    PopplerDocument * poppler_document_new_from_file (const char  *uri, const char  *password,
        GError     **error) {

        PDFDoc *newDoc;
        GooString *password_g;
        char *filename;

        if (!globalParams) {
          globalParams = new GlobalParams();
        }

Any idea how I can create this kind of object?

**Comment by jvolkening** [comment]
The problem is that there is no public interface to this object in the poppler-glib specs. The Perl module is directly tied to poppler-glib using GObject introspection, so any solution would need to be found in poppler-glib. As I see it, there are two possibilities:

1. There is a way to do this, but neither you or I have found it yet by looking at the poppler-glib documentation.

2. There is no current way to do this, so it would require a patch to poppler-glib.

I'll chime in on the poppler mailing list and see if I can expand on the issue.

**Comment by nicolasfranck** [comment]
Ok thanks, I've seen it.

**Comment by nicolasfranck** [comment]
The latest stable built seems to be 0.56. Am I right that you're using version 0.18?

**Comment by jvolkening** [comment]
> The latest stable built seems to be 0.56. Am I right that you're using version 0.18?

The perl module will use whatever version of poppler is on your system. The 0.18 version number refers to the GIR/typelib file -- 0.18 is the version that ships with the latest Debian (which ships v0.46 of popper-glib itself) and, as far as I know, Ubuntu, Arch, etc. Is there something in the latest popper-glib that is missing from the G:I:O interface?

**Comment by nicolasfranck** [comment]
I'm still trying to figure out the exact cause for the different behaviour on some systems.
I'm using travis as a test suite, and travis uses ubuntu by the way.

I tried compiling a C++ example using the poppler source code as delivered by the package libpoppler-cpp-dev, and that worked the same on every version of Ubuntu (as expected)...

...so the problem should be indeed in poppler-glib, not in the core.

BTW I saw this change in version 0.45:
```
return date in UTC instead of local time. Bug #94173
```
which explains why sometimes some tests failed in travis..

So I'll be trying to do the same for the glib interface, so I can send a bug report
to the mailing list. Any ideas on how to start this (libraries I should be linking to?) in C++?

**Comment by jvolkening** [comment]
> Any ideas on how to start this (libraries I should be linking to?) in C++?

poppler-glib is C, so I guess you'd have to start there. I know just enough C/C++ to hang myself, so I can't be much help. I briefly looked at the git history of `GlobalParams.cc` to see if the default value for `textPageBreak` changed at some point, but it has always been the same as far back as I looked.

Can you pinpoint the differences in behavior to a different OS or to differences in poppler version or poppler-glib version? I tested both poppler 0.26 and 0.48 and both give identical output (no line breaks at end of `poppler_page_get_text` return value). Unfortunately I don't have access to any other installed versions to test.

I'm not sure I can be of much more help unless you can show that the issues you observe are actually with the Perl module, but I am curious nonetheless. Can you provide a full test case (example PDF, exact output files showing both behaviors, the exact code you used to generate the outputs)?

**Comment by nicolasfranck** [comment]
I decided to go with more recent operating systems, and leave out those whose live cycles have
ended (e.g. centos 6 and Ubuntu 12). So the return value of poppler_page_get_text becomes better.

I've found some other problems on Centos 7 and Ubuntu 14.

On Centos 7:

  * Installed software:
    * poppler-glib (0.26.5) (from repo base)
    * poppler-glib-devel (0.26.5) (from repo base)
    * gobject-introspection-devel (1.42.0)
  * Problems:
    * perl package Poppler could not be installed:

    ```
    Building Poppler
    WARNING **: Failed to load shared library 'libpoppler-glib.so.8' referenced by the typelib: 
    libpoppler-glib.so.8: cannot open shared object file: No such file or directory at 
    /home/njfranck/perl5/lib/perl5/x86_64-linux-thread-multi/Glib/Object/Introspection.pm line 110.
    Could not locate symbol poppler_document_new_from_file at t/poppler.t line 17
    ```
   
    * I symlinked /usr/lib64/libpoppler-glib.so.8 -> /usr/lib63/libpoppler-glib.so.18.6.0, and Poppler was installed
    * my module Catmandu::Importer::PDF could not be installed:

    ```
    $ cpanm Catmandu::Importer::PDF
    ..
    Building and testing Catmandu-Importer-PDF-0.01
    cp lib/Catmandu/Importer/PDFInfo.pm blib/lib/Catmandu/Importer/PDFInfo.pm
    cp lib/Catmandu/Importer/PDF.pm blib/lib/Catmandu/Importer/PDF.pm
    cp lib/Catmandu/Importer/PDFPages.pm blib/lib/Catmandu/Importer/PDFPages.pm
    t/00-load.t ............ ok

    #   Failed test 'pdf read successfully'
    #   at t/01-pdf.t line 33.
    #     Structures begin differing at:
    #          $got->[0]{document}{modification_date} = '1501050750'
    #     $expected->[0]{document}{modification_date} = '1501057950'
    ```
    * This difference between the modification dates is exactly two hours (diff between UTC and Brussels now), so this is actually due to the bug in Poppler (#94173, see above). I want to deal with this, don't know how to track the version of the loaded poppler library. Any idea?

On Ubuntu Trusty 14:

  * Installed software:
    * libpoppler-glib8 (0.24.5-2ubuntu4)
    * libpoppler-glib-dev (0.24.5-2ubuntu4)
    * libgirepository1.0-dev (1.40.0-1)      

  * Install Poppler fails, due to the newest Glib::Object::Introspection:
  ```
  t/objects.t ................... ok
  **
  ERROR:/usr/share/gobject-introspection-
  1.0/tests/gimarshallingtests.c:5081:gi_marshalling_tests_param_spec_in_bool: assertion failed 
  (G_PARAM_SPEC_TYPE (param) == G_TYPE_BOOLEAN): (9250064 == 20)
  t/param-specs.t ...............
  Failed 7/7 subtests
  t/structs.t ................... ok
  ```
  * Depending on version 0.040 of Glib::Object::Introspection solves the problem
  * Install of my module Catmandu::Importer::PDF still fails due to the same reason mentioned above.

**Comment by jvolkening** [comment]
> I decided to go with more recent operating systems, and leave out those whose live cycles have
> ended (e.g. centos 6 and Ubuntu 12). So the return value of poppler_page_get_text becomes better.

Seems reasonable. Of course it would be trivial to test for the trailing page break in your Perl code and strip if present, if you want to be safe.

> I symlinked /usr/lib64/libpoppler-glib.so.8 -> /usr/lib63/libpoppler-glib.so.18.6.0, and Poppler was installed

I assume you mean `/usr/lib64/libpoppler-glib.so.8.6.0`? This is a distro-specific packaging issue. Debian creates that symlink as part of the package installation. You can talk to the CentOS package maintainer if you are wanting to see this resolved upstream. I do need to update the documentation on package installation to mention some of these potential issues.

> This difference between the modification dates is exactly two hours (diff between UTC and Brussels now), so this is actually due to the bug in Poppler (#94173, see above). I want to deal with this, don't know how to track the version of the loaded poppler library. Any idea?

Generally this is done with `pkg-config` which can be interfaced using `ExtUtils::PkgConfig`, e.g.:

```
use ExtUtils::PkgConfig;
my $modversion = ExtUtils::PkgConfig->modversion('poppler-glib');
```

`ExtUtils::PkgConfig` is already a dependency of `Poppler`, so it should be straightforward to check this in your code.

> Install Poppler fails, due to the newest Glib::Object::Introspection:

To clarify, do you mean the installed version of `Glib::Object::Introspection` was too old or too new? I can certainly bump up the minimum version in the `Build.PL` if needed. Can you tell me the version of `G:O:I` that was installed when you saw these testing errors?

**Comment by nicolasfranck** [comment]
> Generally this is done with pkg-config which can be interfaced using ExtUtils::PkgConfig, e.g.:

Thanks!

> To clarify, do you mean the installed version of Glib::Object::Introspection was too old or too new? I can certainly bump up the minimum version in the Build.PL if needed. Can you tell me the version of G:O:I that was installed when you saw these testing errors?

I just retried, and now it works. Strange ;-)

Thanks for all your help ;-)
